package:
  name: panel-deploy
  version: 0.0.1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - ansible
    - click
    - passlib
    - ruamel.yaml

test:
  requires:
    - pytest >=2.8.5
  imports:
    - panel_deploy

about:
  home: https://github.com/Quansight/panel-deploy
  license: MIT
